### ISSUE TITLE
Constant definition

### ISSUE THREAD

**Issue by rianbooyer** [felixarntz/wp-encrypt#15]
me -"hey was wondering if it was possible to add a way to specify where the keys and certs were saved and what name they would be saved under. 
My situation is this on a godaddy shared hosting site i can get your plugin to work, you have it save to your directories on the server but it would be great if i could specify to save to godaddy's ssl directories instead (key, certs,etc) this way it automatically shows the renewal without having to move the files every 90 days since we don't have access to the virtual machine settings and the ssl redirect can't be put in a .htaccess file.

let me know what you think."

felixarntz - "This is already possible by using a constant (see the Plugin FAQ for instructions)."
------------------------------------------------------------------------------------------------------------------
o.k. could you give me an example of how to do this....also what about renaming the keys from something else besides .pem to .crt .key, etc that can be recognized by sites like godaddy is there a way to define a constant for that? for example godaddy uses the following directories:

ssl
-certs
-csrs
-keys

while yours are all stored in the same directory

**Comment by felixarntz** [comment]
At the moment it is only possible to specify one location which will hold both the certificates and the keys, using the constant `WP_ENCRYPT_SSL_CERTIFICATES_DIR_PATH` (you need to define this in your `wp-config.php`).

I opened #19 to improve that, so that you can store these individually, and #20, so that certificates can be generated in other modes. This functionality will be included in the next version of the plugin.

I'll close this ticket here in favor of these new ones.
