### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by pressbro** [felixarntz/wp-encrypt#17]
Hi! This can be split into several issues. 

- **Multisite**: Generating a certificate upon adding a new site to the network. Currently you need to manually do that each time you add a site, this should be automated.
- **Multisite**: Caching expiration dates on domain so that there would be no need to loop over all of the domains and only loop on those that are needed (new domains, expired domains). 
- **General**: Add a hook for when generation is complete. This is useful to, for example, restart Apache for the new certificates to actually take effect, because without this I need to SSH into the server each time and manually restart Apache. 

There's also the issue of domain mapping on multisite. Since the WPMUDEV domain mapping plugin and the good ol' Multisite Domain Mapping plugin use pretty much the same database schema and are extremely popular with Multisite I think it would be good practice to add support for this as well. Currently this generated certs for only ‘*.mainsite.com‘ and ‘mainsite.com‘, but not for the site's actually used domain if there is domain mapping enabled.

**Comment by pressbro** [comment]
I'll also explain why the first thing should be automated. When one site is on https, then WordPress treats all other sites in the network the same eg. if you go to My Sites, then all the sites there also start with https:// regardless if they actually have a certificate or not - and this causes errors and inconsistency.

**Comment by felixarntz** [comment]
> When one site is on https, then WordPress treats all other sites in the network the same eg. if you go to My Sites, then all the sites there also start with https:// regardless if they actually have a certificate or not - and this causes errors and inconsistency.

While I agree that automating the process might make sense, what you describe here appears to be a bug in WordPress and should be resolved through a [Trac ticket](https://core.trac.wordpress.org/).
Regarding automation, it should be an optional setting though because the process can be time-consuming and (currently) will cause a 500 error if there are too many sites in a multisite and PHP's `max_execution_time` is too low. Improving the latter will be part of #6, but will take some time. Can you open another ticket for triggering renewal when a site is added?

> Caching expiration dates on domain so that there would be no need to loop over all of the domains and only loop on those that are needed (new domains, expired domains).

Unfortunately this isn't possible at the moment because there is only one certificate being generated for all domains, so they all need to be iterated through.

> Add a hook for when generation is complete.

That certainly makes sense, can you open another ticket for this one?

**Comment by pressbro** [comment]
Alright, that makes sense! I've created two new issues for the triggering renewal upon site add and the hook for when certificate generation is complete.
