### ISSUE TITLE
multinetwork subsites

### ISSUE THREAD

**Issue by MarkLimmage** [felixarntz/wp-encrypt#30]
Hi there,

I am using a domain mapping plugin from wpmudev to map domains to my subsites in my mulltnetwork. WP Encrypt generates a certificate for the primary domains of the networks, but does not include the mapped domains of the subsites in the certificate's SAN record.

Is there a way to include more domains in the certificate than just the primary domains in a multinetwork install?

Thanks - Mark

**Comment by felixarntz** [comment]
Hi,

in a Multinetwork you need to enable the option "Global SSL Certificate" to consider all sites in all networks. By default only the sites in the current network are considered.

I hope this helps!

**Comment by MarkLimmage** [comment]
Thanks for getting back to me.  I selected "Global SSL Certificate" and and each of the domains relating to the primary sites of each of the networks were considered in the certificate. My networks are sub-directory networks  with a number of sub-sites in each network. Unique domain names have been mapped to these subsites using wpmudev's [domain mapping](https://premium.wpmudev.org/project/domain-mapping/) however in the multinetwork's sites list the sites are still identified as sub-directories of the primary domains.

Eg 

network1.com
network1.com/subsite1  ==> myfirstsite.com
network1.com/subsite2 ==> mysecondsite.com

network2.com
network2.com/subsite1  ==> mythirdsite.com
network2.com/subsite2 ==> myfourthsite.com

The certificate sucessfully installs and covers network1.com and network2.com (the domains of the primary sites in each network) but the domains of all the subsites are not considred. 

Would manually inserting domain names into the $addon_domains array in ActionHandler.php force the inclusion of these subsite domains the certificate? 

Thanks again for your support.
Mark

**Comment by MarkLimmage** [comment]
Hi again,

I have managed to get the plugin to generate certificates for all the "mapped domains" in my multi-network by simply adding the following line to Util.php at line 322:

`array_push( $addon_domains, 'myfirstsite.com', 'mysecondsite.com' );`

I'd like to get these domains directly from where the domain mapping plugin stores them, but I'm waiting on some advice from the author.

**Comment by felixarntz** [comment]
Ahhh now I see what you mean.

WP Encrypt currently does not support such a domain mapping plugin, since for most cases such a plugin is not necessary as WordPress core already allows setting fully qualified domain names even for subsites (as far as I understand that is what you're using the domain mapping plugin for).

For the few use-cases where one would need to use it, I unfortunately think that a custom solution is the best way to choose here since there are several domain mapping plugins out there, so it's impossible to add support for all of them. If there is an area in WP Encrypt where you would need an additional action or filter hook, I'll gladly introduce it.

**Comment by felixarntz** [comment]
I opened #43 to make this change possible through a filter. Let's continue any discussion needed there. Thanks for bringing this up, and sorry for the waiting time.

I think I might get back to occasionally maintaining this. Any help would be welcome though! :)
